image:
  - Visual Studio 2017

environment:
  matrix:
    - RuntimeURL: https://atom.io/download/atom-shell
      RuntimeName: iojs
      RuntimeVersion: v2.0.8

    - RuntimeURL: https://atom.io/download/atom-shell
      RuntimeName: iojs
      RuntimeVersion: v4.1.4

    - RuntimeURL: https://atom.io/download/atom-shell
      RuntimeName: iojs
<<<<<<< HEAD
      RuntimeVersion: v5.0.0
=======
      RuntimeVersion: v3.0.4
>>>>>>> master

  NodeVersion: 10
  BuildDirectory: build
  Generator: Visual Studio 15 2017 Win64
  DistributeDirectory: distribute
  FullDistributePath: $(BuildDirectory)\$(DistributeDirectory)
  DistributionAritfact: $(RuntimeName)-$(RuntimeVersion)-node-libuiohook

install:
  - ps: Install-Product node $env:NodeVersion
  - yarn install

build_script:
  - cmake -H. -B"%BuildDirectory%" -G"%Generator%"  -DCMAKE_INSTALL_PREFIX="%FullDistributePath%\node-libuiohook" -DNODEJS_NAME=%RuntimeName% -DNODEJS_URL=%RuntimeURL% -DNODEJS_VERSION=%RuntimeVersion%
  - cmake --build %BuildDirectory% --target install --config RelWithDebInfo
  - tar cvaf "%DistributionAritfact%.tar.gz" -C "%FullDistributePath%" "node-libuiohook"

before_deploy:
  - ps: Push-AppveyorArtifact "$env:DistributionAritfact.tar.gz"

deploy:
  - provider: GitHub
    artifact: $(DistributionAritfact).tar.gz
    auth_token:
      secure: nP2TonQxdUNyL65bmBKVPi0/jYX3h6mPCdFgJs1WeD+kNhgoUJ4mqxZ2FWkjpE0N
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true

artifacts:
  - path: $(DistributionAritfact).tar.gz
    name: Distribution Aritfact

test: off